### ISSUE TITLE
wcwidth() returns 1 for unassigned codepoints

### ISSUE THREAD

**Issue by craigbarnes** [richfelker/musl-chartable-tools#5]
It seems as if codepoints that aren't handled by a specific table mapping or condition in musl `wcwidth()` default to a return value of 1. Since unassigned codepoints (i.e. ranges that are [omitted] from `UnicodeData.txt`) have no special handling or lookup table in musl `wcwidth()`, they also default to 1.

However, unassigned codepoints aren't really "printable" in any meaningful sense and even in terminals that produce a visible fallback glyph, it's more often than not a double-width glyph anyway.

One such example is `wcwidth(0x07B2)`, which returns `-1` in glibc, glib and various other wcwidth-like implementations, but `1` in musl `wcwidth()`.

[omitted]: https://www.unicode.org/reports/tr44/tr44-21.html#Default_Values_Table

**Comment by richfelker** [comment]
This is intentional and is a matter of future-proofing. If not for this, it would be impossible to display new characters that the present libc version does not know about in applications which honor wcwidth. Likewise, `iswprint` considers all unicode scalar values except those defined as control characters to be printable, for the same reason.

I'm not sure what you mean by "more often than not a double-width glyph". Most newly-added characters are not double-width except in the CJK planes (2 and 3) where `wcwidth` does return 2 for unassigned codepoints. If a terminal is printing double-width replacement glyphs (and using 2 cells) for characters it's unaware of or that don't yet exist, but that aren't in reserved-for-CJK zones, that seems like a bug in the terminal.

**Comment by craigbarnes** [comment]
> This is intentional and is a matter of future-proofing. If not for this, it would be impossible to display new characters that the present libc version does not know about in applications which honor wcwidth. Likewise, `iswprint` considers all unicode scalar values except those defined as control characters to be printable, for the same reason.

That explanation makes a lot of sense. I just wonder whether or not it's compatible with the ISO C definition (§7.25.2) of a "printing wide character":

> ... a member of a locale-specific set of wide characters, each of which occupies at least one printing position on a display device.

From reading the relevant parts of the C/POSIX/Unicode specs, it all seems very vaguely defined and I guess ultimately just left up to the implementer.

In any case, the use case I had in mind is probably better served by using the Unicode database directly instead of via `wcwidth()`.

**Comment by richfelker** [comment]
> That explanation makes a lot of sense. I just wonder whether or not it's compatible with the ISO C definition (§7.25.2) of a "printing wide character":

Of course it's compatible; it's just a matter of what the implementation defines as the set of characters. Under musl it's all Unicode Scalar Values. The ones that aren't assigned by Unicode are printable as replacement glyphs.

BTW the "at least one" is poor wording in the spec since it seems to preclude nonspacing characters, but such an interpretation is incompatible with any real multilingual use. Rather I think we have to interpret presence of the non-spacing character in a printing position together with the base character it's attached to as "occupying a position".

Ultimately, `isw*` and `wcwidth` need to be defined in a manner that's maximally compatible with ability of users to write/view/process text in their own languages.
